import React from 'react'
import DataTable from '../../components/DataTable'
import { PendingForBatchCreationData, PendingForBatchCreationHeadCell } from '../../utils/types';

function PendingForBatchCreation() {

 const headCells: PendingForBatchCreationHeadCell[] = [
   {
     id: "srno",
     numeric: true,
     disablePadding: false,
     label: "Sr. No.",
   },
   {
     id: "mandateStatus",
     numeric: true,
     disablePadding: false,
     label: "Mandate Status",
   },
   {
     id: "mandateId",
     numeric: true,
     disablePadding: false,
     label: "Mandate ID",
   },
   {
     id: "reference1",
     numeric: true,
     disablePadding: false,
     label: "Reference 1",
   },
   {
     id: "customerName",
     numeric: true,
     disablePadding: false,
     label: "Customer Name",
   },
   {
     id: "customerAccountNo",
     numeric: true,
     disablePadding: false,
     label: "Customer Account No.",
   },
   {
     id: "amount",
     numeric: true,
     disablePadding: false,
     label: "Amount",
   },
   {
     id: "amountInWord",
     numeric: true,
     disablePadding: false,
     label: "Amount In Word",
   },
   {
     id: "IFSC_MICR",
     numeric: true,
     disablePadding: false,
     label: "IFSC/MICR",
   },
   {
     id: "customerBank",
     numeric: true,
     disablePadding: false,
     label: "Customer Bank",
   },
   {
     id: "sponsorBank",
     numeric: true,
     disablePadding: false,
     label: "Sponsor Bank",
   },
   {
     id: "dateOnMandate",
     numeric: true,
     disablePadding: false,
     label: "Date On Mandate",
   },
   {
     id: "formDate",
     numeric: true,
     disablePadding: false,
     label: "Form Date",
   },
   {
     id: "debitTo",
     numeric: true,
     disablePadding: false,
     label: "Debit To",
   },
   {
     id: "debitType",
     numeric: true,
     disablePadding: false,
     label: "Debit Type",
   },
   {
     id: "frequency",
     numeric: true,
     disablePadding: false,
     label: "Frequency",
   },
   {
     id: "createdOn",
     numeric: true,
     disablePadding: false,
     label: "Created On",
   },
   {
     id: "createdBy",
     numeric: true,
     disablePadding: false,
     label: "Created By",
   },
   {
     id: "product",
     numeric: true,
     disablePadding: false,
     label: "Product",
   },
   {
     id: "branch",
     numeric: true,
     disablePadding: false,
     label: "Branch",
   },
   {
     id: "categoryCode",
     numeric: true,
     disablePadding: false,
     label: "Category Code",
   },
   {
     id: "utilityCode",
     numeric: true,
     disablePadding: false,
     label: "Utility Code",
   },
 ];

  function createData(
    id: number,
    srno: number,
    mandateStatus: string,
    mandateId: number,
    reference1: number,
    customerName: string,
    customerAccountNo: number,
    amount: number,
    amountInWord: string,
    IFSC_MICR: string,
    customerBank: string,
    sponsorBank: string,
    dateOnMandate: string,
    formDate: string,
    debitTo: string,
    debitType: string,
    frequency: string,
    createdOn: string,
    createdBy: string,
    product: string,
    branch: string,
    categoryCode: string,
    utilityCode: string
  ): PendingForBatchCreationData {
    return {
      id,
      srno,
      mandateStatus,
      mandateId,
      reference1,
      customerName,
      customerAccountNo,
      amount,
      amountInWord,
      IFSC_MICR,
      customerBank,
      sponsorBank,
      dateOnMandate,
      formDate,
      debitTo,
      debitType,
      frequency,
      createdOn,
      createdBy,
      product,
      branch,
      categoryCode,
      utilityCode,
    };
  }

  const rows = [
    createData(
      1,
      1,
      "Mandate Status",
      1,
      123456789,
      "Customer Name",
      123456789,
      100,
      "One Hundred",
      "ifsc",
      "bank name",
      "sponcer bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "utility code"
    ),
    createData(
      2,
      2,
      "Mandate Status",
      2,
      123456789,
      "Customer Name",
      123456789,
      100,
      "One Hundred",
      "ifsc",
      "bank name",
      "sponcer bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "utility code"
    ),
    createData(
      3, 
      3,
      "Mandate Status",
      3,
      123456789,
      "Customer Name",
      123456789,
      100,
      "One Hundred",
      "ifsc",
      "bank name",
      "sponcer bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "utility code"
    ),
    createData(
      4,
      4,
      "Mandate Status",
      4,
      123456789,
      "Customer Name",
      123456789,
      100,
      "One Hundred",
      "ifsc",
      "bank name",
      "sponcer bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "utility code"
    ),
    createData(
      5,
      5,
      "Mandate Status",
      5,
      123456789,
      "Customer Name",
      123456789,
      100,
      "One Hundred",
      "ifsc",
      "bank name",
      "sponcer bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "utility code"
    ),
    createData(
      6,
      6,
      "Mandate Status",
      6,
      123456789,
      "Customer Name",
      123456789,
      100,
      "One Hundred",
      "ifsc",
      "bank name",
      "sponcer bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "utility code"
    ),
    createData(
      7,
      7,
      "Mandate Status",
      7,
      123456789,
      "Customer Name",
      123456789,
      100,
      "One Hundred",
      "ifsc",
      "bank name",
      "sponcer bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "utility code"
    ),
    createData(
      8,
      8,
      "Mandate Status",
      8,
      123456789,
      "Customer Name",
      123456789,
      100,
      "One Hundred",
      "ifsc",
      "bank name",
      "sponcer bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "utility code"
    ),
  ];

 
  return (
    <DataTable title="Pending For Batch Creation" headCells={headCells} rows={rows}/>
  );
}

export default PendingForBatchCreation