import { SentToBankData, SentToBankHeadCell } from '../../utils/types';
import DataTable from '../../components/DataTable';

function SentToBank() {

  function createData(
    id: number,
    srno: number,
    mandateStatus: string,
    mandateId: number,
    fileNo: number,
    referecne1: number,
    customerName: string,
    customerAccountNo: number,
    amount: number,
    amountInWords: string,
    IFSC_MICR: string,
    customerBank: string,
    sponsorBank: string,
    dateOnMandate: string,
    formDate: string,
    debitTo: string,
    debitType: string,
    frequency: string,
    createdOn: string,
    createdBy: string,
    product: string,
    branch: string,
    categoryCode: string,
    fileId: string,
    initiatedToBankDateAndTime: string,
    utilityCode: string
  ): SentToBankData {
    return {
      id,
      srno,
      mandateStatus,
      mandateId,
      fileNo,
      referecne1,
      customerName,
      customerAccountNo,
      amount,
      amountInWords,
      IFSC_MICR,
      customerBank,
      sponsorBank,
      dateOnMandate,
      formDate,
      debitTo,
      debitType,
      frequency,
      createdOn,
      createdBy,
      product,
      branch,
      categoryCode,
      fileId,
      initiatedToBankDateAndTime,
      utilityCode,
    };
  }

  const rows = [
    createData(
      1,
      1,
      "mandate Status",
      11,
      12,
      13,
      "customer name",
      14,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      2,
      2,
      "mandate Status",
      21,
      22,
      23,
      "customer name",
      24,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      3,
      3,
      "mandate Status",
      31,
      32,
      33,
      "customer name",
      34,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      4,
      4,
      "mandate Status",
      41,
      42,
      43,
      "customer name",
      44,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      5,
      5,
      "mandate Status",
      51,
      52,
      53,
      "customer name",
      54,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      6,
      6,
      "mandate Status",
      61,
      62,
      63,
      "customer name",
      64,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      7,
      7,
      "mandate Status",
      71,
      72,
      73,
      "customer name",
      74,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      8,
      8,
      "mandate Status",
      81,
      82,
      83,
      "customer name",
      84,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      9,
      9,
      "mandate Status",
      91,
      92,
      93,
      "customer name",
      94,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      10,
      10,
      "mandate Status",
      101,
      102,
      103,
      "customer name",
      104,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
    createData(
      11,
      11,
      "mandate Status",
      111,
      112,
      113,
      "customer name",
      114,
      100,
      "One Hundred",
      "ifsc",
      "customer bank",
      "sponsor bank",
      "date on mandate",
      "form date",
      "debit to",
      "debit type",
      "frequency",
      "created on",
      "created by",
      "product",
      "branch",
      "category code",
      "file id",
      "initiated to bank date and time",
      "utility code"
    ),
  ];

  const headCells: SentToBankHeadCell[] = [
    {
      id: "srno",
      numeric: true,
      disablePadding: false,
      label: "Sr. No.",
    },
    {
      id: "mandateStatus",
      numeric: true,
      disablePadding: false,
      label: "Mandate Status",
    },
    {
      id: "mandateId",
      numeric: true,
      disablePadding: false,
      label: "Mandate Id",
    },
    {
      id: "fileNo",
      numeric: true,
      disablePadding: false,
      label: "File No",
    },
    {
      id: "referecne1",
      numeric: true,
      disablePadding: false,
      label: "Referecne 1",
    },
    {
      id: "customerName",
      numeric: true,
      disablePadding: false,
      label: "Customer Name",
    },
    {
      id: "customerAccountNo",
      numeric: true,
      disablePadding: false,
      label: "Customer Account No",
    },
    {
      id: "amount",
      numeric: true,
      disablePadding: false,
      label: "Amount",
    },
    {
      id: "amountInWords",
      numeric: true,
      disablePadding: false,
      label: "Amount In Words",
    },
    {
      id: "IFSC_MICR",
      numeric: true,
      disablePadding: false,
      label: "IFSC/MICR",
    },
    {
      id: "customerBank",
      numeric: true,
      disablePadding: false,
      label: "Customer Bank",
    },
    {
      id: "sponsorBank",
      numeric: true,
      disablePadding: false,
      label: "Sponsor Bank",
    },
    {
      id: "dateOnMandate",
      numeric: true,
      disablePadding: false,
      label: "Date On Mandate",
    },
    {
      id: "formDate",
      numeric: true,
      disablePadding: false,
      label: "Form Date",
    },
    {
      id: "debitTo",
      numeric: true,
      disablePadding: false,
      label: "Debit To",
    },
    {
      id: "debitType",
      numeric: true,
      disablePadding: false,
      label: "Debit Type",
    },
    {
      id: "frequency",
      numeric: true,
      disablePadding: false,
      label: "Frequency",
    },
    {
      id: "createdOn",
      numeric: true,
      disablePadding: false,
      label: "Created On",
    },
    {
      id: "createdBy",
      numeric: true,
      disablePadding: false,
      label: "Created By",
    },
    {
      id: "product",
      numeric: true,
      disablePadding: false,
      label: "Product",
    },
    {
      id: "branch",
      numeric: true,
      disablePadding: false,
      label: "Branch",
    },
    {
      id: "categoryCode",
      numeric: true,
      disablePadding: false,
      label: "Category Code",
    },
    {
      id: "fileId",
      numeric: true,
      disablePadding: false,
      label: "File Id",
    },
    {
      id: "initiatedToBankDateAndTime",
      numeric: true,
      disablePadding: false,
      label: "Initiated To Bank Date And Time",
    },
    {
      id: "utilityCode",
      numeric: true,
      disablePadding: false,
      label: "Utility Code",
    },
  ];
  return <DataTable title="Sent to Bank" headCells={headCells} rows={rows}/>;
}

export default SentToBank