import DataTable from "../../components/DataTable";
import { MandateData, MandateHeadCell } from "../../utils/types";


const headCells : MandateHeadCell[] = [
  {
    id: "srno",
    numeric: true,
    disablePadding: false,
    label: "Sr. No.",
  },
  {
    id: "mandateStatus",
    numeric: true,
    disablePadding: false,
    label: "Mandate Status",
  },
  {
    id: "UMRN",
    numeric: true,
    disablePadding: false,
    label: "UMRN",
  },
  {
    id: "id",
    numeric: true,
    disablePadding: false,
    label: "Mandate ID",
  },
  {
    id: "reference1",
    numeric: true,
    disablePadding: false,
    label: "Reference 1",
  },
  {
    id: "customerName",
    numeric: true,
    disablePadding: false,
    label: "Customer Name",
  },
  {
    id: "customerAccountNo",
    numeric: true,
    disablePadding: false,
    label: "Customer Account No.",
  },
  {
    id: "amount",
    numeric: true,
    disablePadding: false,
    label: "Amount",
  },
  {
    id: "amountInWord",
    numeric: true,
    disablePadding: false,
    label: "Amount in words",
  },
  {
    id: "IFSC_MICR",
    numeric: true,
    disablePadding: false,
    label: "IFSC/MICR",
  },
  {
    id: "customerBank",
    numeric: true,
    disablePadding: false,
    label: "Customer Bank",
  },
  {
    id: "sponsorBank",
    numeric: true,
    disablePadding: false,
    label: "Sponsor Bank",
  },
  {
    id: "dateOnMandate",
    numeric: true,
    disablePadding: false,
    label: "Date on Mandate",
  },
  {
    id: "formDate",
    numeric: true,
    disablePadding: false,
    label: "Form Date",
  },
  {
    id: "debitTo",
    numeric: true,
    disablePadding: false,
    label: "Debit to",
  },
  {
    id: "frequency",
    numeric: true,
    disablePadding: false,
    label: "Frequency",
  },
  {
    id: "mandateType",
    numeric: true,
    disablePadding: false,
    label: "Mandate Type",
  },
  {
    id: "rejectResion",
    numeric: true,
    disablePadding: false,
    label: "Reject Reason",
  },
  {
    id: "createOn",
    numeric: true,
    disablePadding: false,
    label: "Create on",
  },
  {
    id: "createBy",
    numeric: true,
    disablePadding: false,
    label: "Create by",
  },
  {
    id: "lastActivityOn",
    numeric: true,
    disablePadding: false,
    label: "Last Activity on",
  },
  {
    id: "product",
    numeric: true,
    disablePadding: false,
    label: "Product",
  },
  {
    id: "branch",
    numeric: true,
    disablePadding: false,
    label: "Branch",
  },
  {
    id: "categoryCode",
    numeric: true,
    disablePadding: false,
    label: "Category Code",
  },
  {
    id: "utilityCode",
    numeric: true,
    disablePadding: false,
    label: "Utility Code",
  },
];
function createData(
  id: number,
  srno: number,
  mandateStatus: string,
  UMRN: number,
  mandateId: number,
  reference1: number,
  customerName: string,
  customerAccountNo: number,
  amount: number,
  amountInWord: string,
  IFSC_MICR: string,
  customerBank: string,
  sponsorBank: string,
  dateOnMandate: string,
  formDate: string,
  debitTo: string,
  frequency: string,
  mandateType: string,
  rejectResion: string,
  createOn: string,
  createBy: string,
  lastActivityOn: string,
  product: string,
  branch: string,
  categoryCode: string,
  utilityCode: string
): MandateData {
  return {
    id,
    srno,
    mandateStatus,
    UMRN,
    mandateId,
    reference1,
    customerName,
    customerAccountNo,
    amount,
    amountInWord,
    IFSC_MICR,
    customerBank,
    sponsorBank,
    dateOnMandate,
    formDate,
    debitTo,
    frequency,
    mandateType,
    rejectResion,
    createOn,
    createBy,
    lastActivityOn,
    product,
    branch,
    categoryCode,
    utilityCode,
  };
}
const rows = [
  createData(
    1,
    1,
    "status",
    12345,
    1,
    12345,
    "customer",
    12345,
    100,
    "One hundred",
    "12333IFSC",
    "bank",
    "sponsor bank",
    "20/02/2005",
    "20/02/2005",
    "Saving Account",
    "frequency",
    "mandate type",
    "reject resion",
    "20/02/2005",
    "created by",
    "20/02/2005",
    "product",
    "branch",
    "category code",
    "utility code"
  ),
  createData(
    2,
    2,
    "status",
    12345,
    2,
    12345,
    "customer",
    12345,
    100,
    "One hundred",
    "12333IFSC",
    "bank",
    "sponsor bank",
    "20/02/2005",
    "20/02/2005",
    "Saving Account",
    "frequency",
    "mandate type",
    "reject resion",
    "20/02/2005",
    "created by",
    "20/02/2005",
    "product",
    "branch",
    "category code",
    "utility code"
  ),
  createData(
    3,
    3,
    "status",
    12345,
    3,
    12345,
    "customer",
    12345,
    100,
    "One hundred",
    "12333IFSC",
    "bank",
    "sponsor bank",
    "20/02/2005",
    "20/02/2005",
    "Saving Account",
    "frequency",
    "mandate type",
    "reject resion",
    "20/02/2005",
    "created by",
    "20/02/2005",
    "product",
    "branch",
    "category code",
    "utility code"
  ),
  createData(
    4,
    4,
    "status",
    12345,
    4,
    12345,
    "customer",
    12345,
    100,
    "One hundred",
    "12333IFSC",
    "bank",
    "sponsor bank",
    "20/02/2005",
    "20/02/2005",
    "Saving Account",
    "frequency",
    "mandate type",
    "reject resion",
    "20/02/2005",
    "created by",
    "20/02/2005",
    "product",
    "branch",
    "category code",
    "utility code"
  ),
  createData(
    5,
    5,
    "status",
    12345,
    5,
    12345,
    "customer",
    12345,
    100,
    "One hundred",
    "12333IFSC",
    "bank",
    "sponsor bank",
    "20/02/2005",
    "20/02/2005",
    "Saving Account",
    "frequency",
    "mandate type",
    "reject resion",
    "20/02/2005",
    "created by",
    "20/02/2005",
    "product",
    "branch",
    "category code",
    "utility code"
  ),
  createData(
    6,
    6,
    "status",
    12345,
    6,
    12345,
    "customer",
    12345,
    100,
    "One hundred",
    "12333IFSC",
    "bank",
    "sponsor bank",
    "20/02/2005",
    "20/02/2005",
    "Saving Account",
    "frequency",
    "mandate type",
    "reject resion",
    "20/02/2005",
    "created by",
    "20/02/2005",
    "product",
    "branch",
    "category code",
    "utility code"
  ),
];

export default function MandateSearchTab() {
   return <DataTable title="Mandates" headCells={headCells} rows={rows} />;
}
