import DataTable from '../../components/DataTable'
import { UserData, UserHeadCell } from '../../utils/types';

function AllUsers() {

  const headCells: UserHeadCell[] = [
    {
      id: "srno",
      numeric: false,
      disablePadding: true,
      label: "Sr. No.",
    },
    {
      id: "userType",
      numeric: true,
      disablePadding: false,
      label: "User Type",
    },
    {
      id: "userName",
      numeric: true,
      disablePadding: false,
      label: "User Name",
    },
    {
      id: "emailId",
      numeric: true,
      disablePadding: false,
      label: "Email Id",
    },
    {
      id: "phoneNo",
      numeric: true,
      disablePadding: false,
      label: "Phone No.",
    },
    {
      id: "productName",
      numeric: true,
      disablePadding: false,
      label: "Product Name",
    },
    {
      id: "branchName",
      numeric: true,
      disablePadding: false,
      label: "Branch Name",
    },
    {
      id: "lastLogin",
      numeric: true,
      disablePadding: false,
      label: "Last Login",
    },
    {
      id: "createdBy",
      numeric: true,
      disablePadding: false,
      label: "Created By",
    },
    {
      id: "createdOn",
      numeric: true,
      disablePadding: false,
      label: "Created On",
    },
    {
      id: "updatedBy",
      numeric: true,
      disablePadding: false,
      label: "Updated By",
    },
    {
      id: "updatedOn",
      numeric: true,
      disablePadding: false,
      label: "Updated On",
    },
    {
      id: "vendorUser",
      numeric: true,
      disablePadding: false,
      label: "Vendor User",
    },
    {
      id: "accountBlocked",
      numeric: true,
      disablePadding: false,
      label: "Account Blocked",
    },
    {
      id: "status",
      numeric: true,
      disablePadding: false,
      label: "Status",
    },
    {
      id: "mobileApp",
      numeric: true,
      disablePadding: false,
      label: "Mobile App",
    },
  ];

  function createData(
    id: number,
    srno: number,
    userType: string,
    userName: string,
    emailId: string,
    phoneNo: number,
    productName: string,
    branchName: string,
    lastLogin: string,
    createdBy: string,
    createdOn: string,
    updatedBy: string,
    updatedOn: string,
    vendorUser: string,
    accountBlocked: string,
    status: string,
    mobileApp: string
  ): UserData {
    return {
      id,
      srno,
      userType,
      userName,
      emailId,
      phoneNo,
      productName,
      branchName,
      lastLogin,
      createdBy,
      createdOn,
      updatedBy,
      updatedOn,
      vendorUser,
      accountBlocked,
      status,
      mobileApp,
    };
  }

  const rows = [
    createData(
      0,
      0,
      "user type",
      "sagar",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      1,
      1,
      "user type",
      "sagar",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      2,
      2,
      "user type",
      "Sagar",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      3,
      3,
      "user type",
      "user name 3",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      4,
      4,
      "user type",
      "user name 4",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      5,
      5,
      "user type",
      "user name 5",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      6,
      6,
      "user type",
      "user name 6",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      7,
      7,
      "user type",
      "user name 7",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      8,
      8,
      "user type",
      "user name 8",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
    createData(
      9,
      9,
      "user type",
      "user name 9",
      "email id",
      1234567890,
      "product name",
      "branch",
      "01/01/0001",
      "created by",
      "01/01/0001",
      "updated by",
      "01/01/0001",
      "vendor user",
      "Account blocked",
      "status",
      "mobile app"
    ),
  ];
  return <DataTable title="User Creation" rows={rows} headCells={headCells} />;
}

export default AllUsers